/**
 * This Java source file was generated by the Gradle 'init' task.
 */
/**
 * ≤‚ ‘
 * @author Admin
 *
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
